apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tan-dara5304-gradle-spring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/tan-dara5304-gradle-spring.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: tan-dara5304-gradle-spring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
