apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tan-dara5304-gradle-spring-certificate
  namespace: tan-dara5304-gradle-spring
spec:
  secretName: tan-dara5304-gradle-spring-secret-tls
  commonName: tan-dara5304-gradle-spring.assessify.org
  dnsNames:
  - tan-dara5304-gradle-spring.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
